conky.config = {
    alignment = 'top_right',
    background = true,
    own_window = true,
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 230,
    own_window_colour = '1E2127',
    gap_x = 30,
    gap_y = 60,
    minimum_width = 300,
    update_interval = 5.0,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=9',
    color0 = '61AFEF',
    color3 = 'FFFFFF',
}

conky.text = [[
${color0}DEBUG OUTPUT:
${color3}${exec ~/.config/conky/format-prayer-times.sh}
]]
