;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================


[colors]
blue-gray = #5f6f7f
background = #1E2127
background-alt = #282B31
foreground = #FFFFFF
primary = #61AFEF
secondary = #98C379
alert = #E06C75
disabled = #5C6370
border-clr = #61AFEF

[bar/example]
width = 100%
height = 20pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
border-size = 0

padding-left = 0
padding-right = 1
module-margin = 1

separator = " | "
separator-foreground = ${colors.disabled}

font-0 = Ubuntu Nerd Font:style=Regular:pixelsize=11;1

modules-left = xworkspaces
modules-center = date
;modules-right = pulseaudio memory cpu systray battery powermenu
modules-right = mic pulseaudio memory cpu; battery
cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = i3

;==========================================================
; MODULES
;==========================================================

[module/powermenu]
type = custom/script
exec = echo "" $(whoami)
format-prefix = " "
format-prefix-foreground = ${colors.primary}
;click-left = rofi -show power-menu -modi power-menu:rofi-power-menu
click-left = ~/.config/rofi/powermenu/powermenu.sh

[module/systray]
type = internal/tray
format-margin = 2pt
tray-spacing = 10pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.blue-gray}
label-active-foreground = ${colors.primary}
label-active-padding = 2

label-occupied = %name%
label-occupied-padding = 2

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%

[module/mic]
type = custom/script
exec = ~/.local/bin/mic-toggle.sh status
click-left = ~/.local/bin/mic-toggle.sh toggle
format-foreground = ${colors.primary}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.primary}
label-volume = %percentage%%

label-muted = " 0%"
label-muted-foreground = ${colors.primary}

;[module/memory]
;type = internal/memory
;interval = 2
;format-prefix = "󰘚 "
;format-prefix-foreground = ${colors.primary}
;label = %percentage_used%%

;[module/cpu]
;type = internal/cpu
;interval = 2
;format-prefix = "󰍛 "
;format-prefix-foreground = ${colors.primary}
;label = %percentage%%


[module/memory]
type = custom/script
exec = ~/.config/polybar/scripts/ram.sh
interval = 2
format-prefix = "󰘚 "
format-prefix-foreground = ${colors.primary}

[module/cpu]
type = custom/script
exec = ~/.config/polybar/scripts/cpu.sh
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}

;[module/gpu]
;type = custom/script
;exec = ~/.config/polybar/scripts/gpu.sh
;interval = 2
;format-prefix = "󰍹 "
;format-prefix-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 1
date = %I:%M %p
date-alt = %d %B %Y %I:%M %p
label = %{F#ffffff}%date%%{F-}
label-foreground = ${colors.primary}

;[module/battery]
;type = internal/battery
;battery = BAT1
;adapter = ACAD
;full-at = 100

; Icons for different battery states (Nerd Font)
;label-charging = "󰂀 %percentage%%" 
;label-discharging = "󰁹 %percentage%%"
;label-full =  "󰂄 %percentage%%"

format = <label>

; Colors for different states
label-charging-foreground = ${colors.primary}
label-discharging-foreground = ${colors.alert}
label-full-foreground = ${colors.primary}


[settings]
screenchange-reload = true
pseudo-transparency = true
